### ISSUE TITLE
app crushes iOS and android after start/installation

### ISSUE THREAD

**Issue by simonettoa** [EddyVerbruggen/nativescript-pluginshowcase#10]
I've just cloned the app and tried to run it; first in iOS - build ok, the app is installed and the green launch page is loading but then crashes and I've got this error:

> Refreshing application...
Successfully synced application org.nativescript.pluginshowcase on device C7DBD6AF-3B62-49BD-9EA7-84841AF63850.
Executing before-watch hook from /Users/asimonetto/Progetti/NativeScript/Rete/nativescript-pluginshowcase/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.6.2
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1109a9724 -[TNSRuntime executeModule:referredBy:]
2   0x10fd94671 main
3   0x116776d81 start
JavaScript stack trace:
1   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:158:26
2   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:92:38
3   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:81:26
4   anonymous@file:///app/main.js:4:57
5   evaluate@[native code]
6   moduleEvaluation@[native code]
7   @[native code]
8   promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-angular/platform-common.js:158:26: JS ERROR TypeError: application_1.run is not a function. (In 'application_1.run()', 'application_1.run' is undefined)
14:24:18 - Compilation complete. Watching for file changes.

In android similar behaviour but after the installation on device I got this:

> Refreshing application...
Successfully synced application org.nativescript.pluginshowcase on device 192.168.58.101:5555.
Executing before-watch hook from /Users/asimonetto/Progetti/NativeScript/Rete/nativescript-pluginshowcase/hooks/before-watch/nativescript-dev-typescript.js
Found peer TypeScript 2.6.2
ActivityManager: Start proc 3415:org.nativescript.pluginshowcase/u0a206 for activity org.nativescript.pluginshowcase/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: TypeError: application_1.run is not a function
System.err: File: "file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js, line: 158, column: 22
System.err: StackTrace: 
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapNativeScriptApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 158, column: 23
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 92, column: 14
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 81, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/main.js', line: 4, column: 42
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: TypeError: application_1.run is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapNativeScriptApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 158, column: 23
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 92, column: 14
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 81, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/main.js', line: 4, column: 42
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
System.err: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: TypeError: application_1.run is not a function
System.err: File: "file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js, line: 158, column: 22
System.err: StackTrace: 
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapNativeScriptApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 158, column: 23
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 92, column: 14
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 81, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/main.js', line: 4, column: 42
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: TypeError: application_1.run is not a function
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapNativeScriptApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 158, column: 23
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapApp', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 92, column: 14
System.err: 	Frame: function:'NativeScriptPlatformRef.bootstrapModule', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/platform-common.js', line: 81, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.pluginshowcase/files/app/main.js', line: 4, column: 42
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:530)
System.err: 	at com.tns.Runtime.run(Runtime.java:522)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
System.err: 	... 8 more
ActivityManager: Process org.nativescript.pluginshowcase (pid 3415) has died
14:28:18 - Compilation complete. Watching for file changes.

Also my colleague tried in his mac, same behaviour.

**Comment by simonettoa** [comment]
find the problem, in package.json the library version 

> "nativescript-angular": "~5.3.0-2018-02-22-01",

creates the issue, I've set back to 

> "nativescript-angular": "~5.2.0",

and it works!

**Comment by EddyVerbruggen** [comment]
Thanks, I was testing some bleeding edge feature and didn't really meant to check that in anyway. Reverted! 👍

**Comment by thanhdevapp** [comment]
Thanks, It's work
