### ISSUE TITLE
Runs, but with exceptions and no navigation

### ISSUE THREAD

**Issue by vbudilov** [EddyVerbruggen/nativescript-pluginshowcase#2]
First of all thanks for the app!

I've cloned it and ran tns run android. It loaded on my phone but with some exceptions. The app loads but the Navigation Drawer's links don't work (except the bottom one where it has your twitter account). 

Any idea what could be wrong? Is it most-likely a versioning issue on my phone? Moto Z Play, Android v7.1.1. 
tns doctor shows 'all good'. 

Build exceptions:
`Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Skip android.databinding.DataBindingUtil
        Error: java.lang.NullPointerException
Skip android.databinding.ViewDataBinding
        Error: java.lang.NullPointerException
Skip android.databinding.adapters.CardViewBindingAdapter
        Error: java.lang.NullPointerException
Skip timber.lint.WrongTimberUsageDetector
        Error: java.lang.NullPointerException
Project successfully built.
`

Runtime exceptions: 

`
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/forms/value-accessors/base-value-accessor", relative to: app/tns_modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:953)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:937)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:929)
JS:     com.tns.gen.android.app.Application_ActivityLifecycleCallbacks.onActivityResumed(Application_ActivityLifecycleCallbacks.java:24)
JS:     android.app.Application.dispatchActivityResumed(Application.java:216)
JS:     android.app.Activity.onResume(Activity.java:1255)
JS:     android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
JS:     android.app.Activity.performResume(Activity.java:6791)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3427)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749)
JS:     android.app.ActivityThread.-wrap12(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6165)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
JS: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular/forms/value-accessors/base-value-accessor", relative to: app/tns_modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:953)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:937)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:929)
JS:     com.tns.gen.android.app.Application_ActivityLifecycleCallbacks.onActivityResumed(Application_ActivityLifecycleCallbacks.java:24)
JS:     android.app.Application.dispatchActivityResumed(Application.java:216)
JS:     android.app.Activity.onResume(Activity.java:1255)
JS:     android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1291)
JS:     android.app.Activity.performResume(Activity.java:6791)
JS:     android.app.ActivityThread.performResumeActivity(ActivityThread.java:3427)
JS:     android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3490)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2749)
JS:     android.app.ActivityThread.-wrap12(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6165)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-drop-down/angular/index.js:6:29)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.pluginshowcase/files/app/ar/ar.module.js:7:17)
JS:     at require (<anonymous>:1:266)
JS:     at requireModule (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/router/ns-module-factory-loader.js:30:31)
JS:     at NSModul
JS: eFactoryLoader.loadAndCompile (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/router/ns-module-factory-loader.js:17:22)
JS:     at NSModuleFactoryLoader.load (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/nativescript-angular/router/ns-module-factory-loader.js:14:18)
JS:     at RouterConfigLoader.loadModuleFactory (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:3418:72)
JS:     at RouterConfigLoader.load (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:3402:52)
JS:     at file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:5657:57
JS:     at PreloadAllModules.preload (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:5552:48)
JS:     at RouterPreloader.preloadConfig (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:5656:40)
JS:     at RouterPreloader.processRoutes (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:5640:31)
JS:     at RouterPreloader.processRoutes (file:///data/data/org.nativescript.pluginshowcase/files/app/tns_modules/@angular/router/bundles/router.umd.js:5644:31)
ActivityManager: Killing 6363:org.nativescript.pluginshowcase/u0a152 (adj 904): remove task
ActivityManager: cleanUpApplicationRecord -- 6363
`

**Comment by EddyVerbruggen** [comment]
Hi, that’s good to know, thx for the info. 

Can you please also try the Google Play version to see if that works?

**Comment by alexzaganelli** [comment]
Hi, it's the same for me. Instead the App Store version works well on my iPhone 6S w/ iOS 11.0.1

**Comment by EddyVerbruggen** [comment]
Thanks guys. I don't have the same issue, but it seems like a problem in nativescript-angular that has been solved a while ago. Let me update all libraries to their latest versions and push an update.

**Comment by EddyVerbruggen** [comment]
Dependencies updated: {N} 3.3 and Angular 4.4.x, and pinned a few deps more aggressively. Hope that helps!

**Comment by vbudilov** [comment]
All fixed, thanks!
