### ISSUE TITLE
How to get back to HomeComponent?

### ISSUE THREAD

**Issue by NickAtGit** [EddyVerbruggen/nativescript-pluginshowcase#21]
Hi Eddy,

I am teaching myself how Nativescript works with your project and I was wondering, how would one go back to the HomeComponent? I would love to see that as an improvement in the plugin showcase :) 

Thanks for the great project!

**Comment by EddyVerbruggen** [comment]
Hi,

I've deliberately not added a way to go back to home because there's no use.

Otherwise, it's a route like all the others, but instead of going to `/speech`, you'd go to `/`.
