### ISSUE TITLE
something went wrong while installing

### ISSUE THREAD

**Issue by SomeDudeeee** [EddyVerbruggen/nativescript-pluginshowcase#24]
hi,

I just wanted to try out this app so I cloned the repo and connected my phone via adb over wifi, i used tns run android and after building it, the command line said that it sucessfully installed the app but there was no trace of it to be found on my phone while I also lost about 500mb storage.

The app didn't show up in the app drawer, I couldn't fine any files in the android data folder and even poking around in the system files was unsuccessful, i then tried to run it again and it worked but my storage is still used up..

any ideas where the files pushed by adb could be?

thanks

**Comment by EddyVerbruggen** [comment]
No idea. Google it, I’d say..
