### ISSUE TITLE
Access to spoken audio

### ISSUE THREAD

**Issue by suparnavg** [EddyVerbruggen/nativescript-pluginshowcase#25]
@EddyVerbruggen Thanks for this excellent plugin. Installs and starts working like a charm!

I'm wondering if there's a way to get access to the spoken / recorded audio? Sort of like the recorder in nativescript-audio.

My nativescript+angular application requires persistent storage of both the audio and the speech2text function's recognized text - would be great if this is something that can be accomplished with this plugin itself.

Thanks!

**Comment by EddyVerbruggen** [comment]
See https://github.com/EddyVerbruggen/nativescript-speech-recognition/issues/20

**Comment by suparnavg** [comment]
Thanks @EddyVerbruggen. If you're curious about this issue I've documented what I've tried with the nativescript-audio plugin and the Google Speech API and why it doesn't seem to be working in [this issue](https://github.com/nstudio/nativescript-audio/issues/114).
