### ISSUE TITLE
iOS Firebase Crashes

### ISSUE THREAD

**Issue by aguglie** [EddyVerbruggen/nativescript-pluginshowcase#26]
Hi :) 
On iOS everything works except the firebase tab. When I click the app crashes, i'm running iOS 12.1

**Comment by EddyVerbruggen** [comment]
Hi! I guess I'll need to bump a few dependencies. No time... no time.. 😔

**Comment by EddyVerbruggen** [comment]
I think it's because of some erroneous data (a city without a name or something) that was entered on the Firebase tab. It's probably my silly sorting logic that's to blame here. I removed the data - does it work now?

**Comment by aguglie** [comment]
Nope, still crashing ☹️

**Comment by EddyVerbruggen** [comment]
Thanks for letting me know. I have it running on an iPhone X. What's your model?

**Comment by aguglie** [comment]
Whoops, I deleted then installed again and now it’s working on my iPhone 6S 😊
Maybe there was some caching issue?
Thanks

**Comment by EddyVerbruggen** [comment]
That could very well be - I think Firebase uses whatever is cached locally until it synced with the cloud (which it could never do). I'll fix the bug that allowed invalid data to be entered. Thanks for the quick check!
