### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by lanbau** [EddyVerbruggen/nativescript-pluginshowcase#27]
hi i downloaded your app on Huawei P20 Pro. It's a great project! 

Everything works except the Firebase tab. Whenever i load that page it closes the app automatically.

Hope this is an easy fix, still thinking whether to jump from cordova to nativescript.

**Comment by EddyVerbruggen** [comment]
I think it's because of some erroneous data (a city without a name or something) that was entered on the Firebase tab. It's probably my silly sorting logic that's to blame here. I removed the data - does it work now?

**Comment by lanbau** [comment]
Hey @EddyVerbruggen,

Yes it works now! awesome stuff.

Thanks
