### ISSUE TITLE
[Question] How to set the status bar's background color to transparent

### ISSUE THREAD

**Issue by vahidvdn** [EddyVerbruggen/nativescript-pluginshowcase#28]
Hey @EddyVerbruggen 
How did you set the status bar's background color to transparent in android?

**Comment by EddyVerbruggen** [comment]
Must have been this: https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/master/app/utils/status-bar-util.ts

**Comment by vahidvdn** [comment]
@EddyVerbruggen Have you ever tested it in NativeScript 5.x ? (My version is 5.3)

It doesn't work for me. (Your app seems fine on my phone, but `status-bar-util` doesn't work fine for my app.

**Comment by EddyVerbruggen** [comment]
Nope. Has been a while since I had time to touch this app.
