### ISSUE TITLE
Feedback errors on devices when preview

### ISSUE THREAD

**Issue by cherimo** [EddyVerbruggen/nativescript-pluginshowcase#29]
Hey,

I am fresh to Nativescript, I run into a problem which I cant get fixed.
When i'm testing it within the emulator everything works fine, but when I preview it on my android and iPhone device its giving the next error:

IOS:
ERROR Error: Uncaught (in promise): ReferenceError: Can't find variable: ISMessages

Android:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'alerter' of undefined

I already tried to remove the platforms and rebuild it again, but unfortunately no luck.
Is there maybe another solution?

PS: Thanks for everything :)

**Comment by EddyVerbruggen** [comment]
This repo needs updating, I don't think it's too compatible with the latest NativeScript release. If you want to learn NativeScript please look elsewhere for now.
