### ISSUE TITLE
Device locale for speech-recognition plugin

### ISSUE THREAD

**Issue by andreapavoni** [EddyVerbruggen/nativescript-pluginshowcase#7]
Hi there,

first of all, thank you for this funny project. I've installed it on my iphone to see how NativeScript and its plugins work for a real app. In particular, I was interested in the speech recognition plugin.

My phone locale is italian, but the speech recognition plugin defaults to english if a locale is not specified. So, when I tested it by speaking in italian, it didn't understand my language. Well, it did it very poorly :-P

I still don't know NativeScript, but I've seen there's some function to get the device locale. It would be very useful to automatically recognize && set the locale or even choose it from a list should be ok as well. Do you think it's a possible addition?

thank you in advance!

**Comment by EddyVerbruggen** [comment]
Yeah it's English on purpose but indeed it can be changed to the device locale. Both for text-to-speech and speech-to-text. Would you be up for a PR?

**Comment by andreapavoni** [comment]
Hi @EddyVerbruggen , thank you for the quick and kind reply!

I still haven't studied NativeScript/TypeScript at all, but luckily I was able to understand some bits by reading sources. In this comment I'm going to talk about the the _speech_ plugins projects, I'm not cross-posting just to keep the things in a unique place.

Maybe I'm wrong, but it looks like the problem relies on the plugins, not on the demo app. In fact, the demo app says that if a locale is not specified, it should recognize it automatically ([here](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/master/app/speech/speech.component.ts#L149) and [here](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/master/app/speech/speech.component.ts#L183) are the interesting lines).

So, I went to check on the plugins, and I've found that (or, at least, it looks so to me) that the locale is not explicitly recognized. For example, in the speech-to-text plugin there are these lines: https://github.com/EddyVerbruggen/nativescript-speech-recognition/blob/master/speech-recognition.ios.ts#L38-L43

Honestly, I don't know if `SFSpeechRecognizer.new();` fallbacks to device locale by default, but perhaps it doesn't work as expected. Even in the `nativescript-speech-recognition`'s demo, locales are explicitly specified by hand (NL and EN).

A possible solution, as far as I understood, might be to use `device.language` from the `platform` module. Maybe the best place would be in the plugins rather than on this project, so that it's much coherent. What do you think?

Thanks in advance

**Comment by EddyVerbruggen** [comment]
Hi @andreapavoni, thanks for looking into it. You are right, `device.language` is better and I've changed the implementation of the plugin. The next version of this app will include the update. 👍
